# **Genomic analysis of malaria vectors in The Gambia**

### **Carboxylesterase loci data exploration**  _ Supplementary Figures S8 & S9

- In this notebook, we explore CNV in the COE loci following the detection of signal of selection in *Anopheles arabiensis* from the coast of Gambia

In [ ]:
!pip install -q malariagen_data

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 29.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 263.7/263.7 kB 19.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.7/71.7 kB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 8.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 81.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 775.9/775.9 kB 28.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.8/47.8 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 104.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.7/25.7 MB 10.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 90.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.3/211.3 kB 10.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 83.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.3/87.3 kB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.0/228.0 kB 14.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.3/14.3 MB 75.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 75.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 336.2/336.2 kB 21.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.2/88.2 kB 6.0 MB/s eta 0:00:00
  Building wheel for dash-cytoscape (setup.py) ... done
  Building wheel for asciitree (setup.py) ... done

In [ ]:
!pip install -q "plotly<6" kaleido==0.2.1

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 MB 11.4 MB/s eta 0:00:00

In [ ]:
import os
import malariagen_data
import kaleido
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import bokeh.io as bkio
bkio.output_notebook()

In [ ]:
try:
    from google.colab import drive, output
    output.enable_custom_widget_manager()
    drive.mount("drive")
    base_dir = "drive/MyDrive/Colab Data/gm-analysis"
except ImportError:
    base_dir = "../results/gm-analysis"

results_dir = os.path.join(base_dir, "Snp_Cnv_freq-results")

Mounted at drive

In [ ]:
git_dir = "/content/drive/My Drive/Colab Data/divergent-genetic-insecticide-resistance-in-gambian-malaria-vector"
try:
  figures_dir = os.path.join(git_dir, "figures")
except NameError:
  figures_dir = "../figures"
os.makedirs(results_dir, exist_ok=True)

In [ ]:
ag3 = malariagen_data.Ag3(pre=True)
ag3

<MalariaGEN Ag3 API client>
Storage URL                           : gs://vo_agam_release_master_us_central1/
Data releases available               : 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12, 3.13, 3.14, 3.15, 3.16, 3.17
Results cache                         : None
Cohorts analysis                      : 20260120
AIM analysis                          : 20220528
Site filters analysis                 : dt_20200416
Software version                      : malariagen_data 15.10.0
Client location                       : Utah, United States (Google Cloud us-west3)
Data filtered to unrestricted use only: False
Data filtered to surveillance use only: False
Relevant data releases                : 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12, 3.13, 3.14, 3.15, 3.16, 3.17
---
Please note that data are subject to terms of use,
for more information see the Vector Observatory website https://www.malariagen.net/vobs/
or contact support@malariagen.net. For API documentation see
https://malariagen.github.io/malariagen-data-python/v15.10.0/Ag3.html

In [ ]:
gambia_sample_query = "country == 'Gambia, The' and sample_set == '1272-VO-GM-OPONDO-VMF00160' and taxon == 'arabiensis' and sample_id!='VBS47740-6366STDY9854349' and unrestricted_use == True"

In [ ]:
# access metadata
df_samples_gambia = ag3.sample_metadata(sample_query=gambia_sample_query)
df_samples_gambia

,sample_id,partner_sample_id,contributor,country,location,year,month,latitude,longitude,sex_call,...,admin1_name,admin1_iso,admin2_name,taxon,cohort_admin1_year,cohort_admin1_month,cohort_admin1_quarter,cohort_admin2_year,cohort_admin2_month,cohort_admin2_quarter
0,VBS47723-6366STDY9854332,C0454,Kevin Opondo,"Gambia, The",Dongoroba,2019,9,13.380,-15.294,F,...,Mansakonko,GM-L,Jarra East,arabiensis,GM-L_arab_2019,GM-L_arab_2019_09,GM-L_arab_2019_Q3,GM-L_Jarra-East_arab_2019,GM-L_Jarra-East_arab_2019_09,GM-L_Jarra-East_arab_2019_Q3
1,VBS47725-6366STDY9854334,C2409,Kevin Opondo,"Gambia, The",Kerewan,2019,9,13.515,-14.896,F,...,Janjanbureh,GM-M,Lower Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_09,GM-M_arab_2019_Q3,GM-M_Lower-Fuladu-West_arab_2019,GM-M_Lower-Fuladu-West_arab_2019_09,GM-M_Lower-Fuladu-West_arab_2019_Q3
2,VBS47726-6366STDY9854335,C0587,Kevin Opondo,"Gambia, The",Bansang,2019,9,13.434,-14.655,F,...,Janjanbureh,GM-M,Upper Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_09,GM-M_arab_2019_Q3,GM-M_Upper-Fuladu-West_arab_2019,GM-M_Upper-Fuladu-West_arab_2019_09,GM-M_Upper-Fuladu-West_arab_2019_Q3
3,VBS47729-6366STDY9854338,C2710,Kevin Opondo,"Gambia, The",Boiram,2019,10,13.503,-14.926,F,...,Janjanbureh,GM-M,Lower Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_10,GM-M_arab_2019_Q4,GM-M_Lower-Fuladu-West_arab_2019,GM-M_Lower-Fuladu-West_arab_2019_10,GM-M_Lower-Fuladu-West_arab_2019_Q4
4,VBS47731-6366STDY9854340,C2524,Kevin Opondo,"Gambia, The",Bansang,2019,9,13.434,-14.655,F,...,Janjanbureh,GM-M,Upper Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_09,GM-M_arab_2019_Q3,GM-M_Upper-Fuladu-West_arab_2019,GM-M_Upper-Fuladu-West_arab_2019_09,GM-M_Upper-Fuladu-West_arab_2019_Q3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309,VBS48167-6366STDY9854768,W1491,Kevin Opondo,"Gambia, The",Essau,2019,10,13.481,-16.515,F,...,Kerewan,GM-N,Lower Niumi,arabiensis,GM-N_arab_2019,GM-N_arab_2019_10,GM-N_arab_2019_Q4,GM-N_Lower-Niumi_arab_2019,GM-N_Lower-Niumi_arab_2019_10,GM-N_Lower-Niumi_arab_2019_Q4
310,VBS48171-6366STDY9854772,W2321,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.290,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
311,VBS48173-6366STDY9854774,W0382,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3
312,VBS48174-6366STDY9854775,W1168,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3
313,VBS48175-6366STDY9854776,W1807,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.290,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3

In [ ]:
df_sample_sets = ag3.sample_sets(release=["3.0", "3.5"])
df_sample_sets

,sample_set,sample_count,study_id,study_url,terms_of_use_expiry_date,terms_of_use_url,release,unrestricted_use
0,AG1000G-AO,81,AG1000G-AO,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
1,AG1000G-BF-A,181,AG1000G-BF-1,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
2,AG1000G-BF-B,102,AG1000G-BF-1,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
3,AG1000G-BF-C,13,AG1000G-BF-2,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
4,AG1000G-CD,76,AG1000G-CD,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
5,AG1000G-CF,73,AG1000G-CF,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
6,AG1000G-CI,80,AG1000G-CI,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
7,AG1000G-CM-A,303,AG1000G-CM-1,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
8,AG1000G-CM-B,97,AG1000G-CM-2,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
9,AG1000G-CM-C,44,AG1000G-CM-3,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
10,AG1000G-FR,23,AG1000G-FR,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
11,AG1000G-GA-A,69,AG1000G-GA-1,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
12,AG1000G-GH,100,AG1000G-GH,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
13,AG1000G-GM-A,74,AG1000G-GM-1,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
14,AG1000G-GM-B,31,AG1000G-GM-2,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
15,AG1000G-GM-C,174,AG1000G-GM-3,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
16,AG1000G-GN-A,45,AG1000G-GN-ML,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
17,AG1000G-GN-B,185,AG1000G-GN-ML,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
18,AG1000G-GQ,10,AG1000G-GQ,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
19,AG1000G-GW,101,AG1000G-GW,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
20,AG1000G-KE,86,AG1000G-KE,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
21,AG1000G-ML-A,60,AG1000G-ML-1,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
22,AG1000G-ML-B,71,AG1000G-ML-2,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
23,AG1000G-MW,41,AG1000G-MW,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
24,AG1000G-MZ,74,AG1000G-MZ,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
25,AG1000G-TZ,300,AG1000G-TZ,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
26,AG1000G-UG,290,AG1000G-UG,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
27,AG1000G-X,669,AG1000G-X,https://www.malariagen.net/partner_study/AG100...,2025-01-01,https://www.malariagen.net/data/our-approach-s...,3.0,True
28,1264-VO-CD-WATSENGA-VMF00161,508,1264-VO-CD-WATSENGA,https://www.malariagen.net/partner_study/1264-...,2025-11-17,https://malariagen.github.io/vector-data/ag3/a...,3.5,True
29,1264-VO-CD-WATSENGA-VMF00164,165,1264-VO-CD-WATSENGA,https://www.malariagen.net/partner_study/1264-...,2025-05-12,https://malariagen.github.io/vector-data/ag3/a...,3.5,True
30,1270-VO-MULTI-PAMGEN-VMF00162,85,1270-VO-MULTI-PAMGEN,https://www.malariagen.net/partner_study/1270-...,2025-11-17,https://malariagen.github.io/vector-data/ag3/a...,3.5,True
31,1272-VO-GM-OPONDO-VMF00160,382,1272-VO-GM-OPONDO,https://www.malariagen.net/partner_study/1272-...,2025-11-17,https://malariagen.github.io/vector-data/ag3/a...,3.5,True

In [ ]:
df_samples_gambia.columns

Index(['sample_id', 'partner_sample_id', 'contributor', 'country', 'location',
       'year', 'month', 'latitude', 'longitude', 'sex_call', 'sample_set',
       'release', 'quarter', 'study_id', 'study_url',
       'terms_of_use_expiry_date', 'terms_of_use_url', 'unrestricted_use',
       'mean_cov', 'median_cov', 'modal_cov', 'mean_cov_2L', 'median_cov_2L',
       'mode_cov_2L', 'mean_cov_2R', 'median_cov_2R', 'mode_cov_2R',
       'mean_cov_3L', 'median_cov_3L', 'mode_cov_3L', 'mean_cov_3R',
       'median_cov_3R', 'mode_cov_3R', 'mean_cov_X', 'median_cov_X',
       'mode_cov_X', 'frac_gen_cov', 'divergence', 'contam_pct', 'contam_LLR',
       'is_surveillance', 'aim_species_fraction_arab',
       'aim_species_fraction_colu', 'aim_species_fraction_colu_no2l',
       'aim_species_gambcolu_arabiensis', 'aim_species_gambiae_coluzzii',
       'aim_species', 'country_iso', 'admin1_name', 'admin1_iso',
       'admin2_name', 'taxon', 'cohort_admin1_year', 'cohort_admin1_month',
       'cohort_admin1_quarter', 'cohort_admin2_year', 'cohort_admin2_month',
       'cohort_admin2_quarter'],
      dtype='object')

In [ ]:
df_samples_gambia.query("sample_set == '1272-VO-GM-OPONDO-VMF00160' and taxon == 'arabiensis'and sample_id!='VBS47740-6366STDY9854349'")

,sample_id,partner_sample_id,contributor,country,location,year,month,latitude,longitude,sex_call,...,admin1_name,admin1_iso,admin2_name,taxon,cohort_admin1_year,cohort_admin1_month,cohort_admin1_quarter,cohort_admin2_year,cohort_admin2_month,cohort_admin2_quarter
0,VBS47723-6366STDY9854332,C0454,Kevin Opondo,"Gambia, The",Dongoroba,2019,9,13.380,-15.294,F,...,Mansakonko,GM-L,Jarra East,arabiensis,GM-L_arab_2019,GM-L_arab_2019_09,GM-L_arab_2019_Q3,GM-L_Jarra-East_arab_2019,GM-L_Jarra-East_arab_2019_09,GM-L_Jarra-East_arab_2019_Q3
1,VBS47725-6366STDY9854334,C2409,Kevin Opondo,"Gambia, The",Kerewan,2019,9,13.515,-14.896,F,...,Janjanbureh,GM-M,Lower Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_09,GM-M_arab_2019_Q3,GM-M_Lower-Fuladu-West_arab_2019,GM-M_Lower-Fuladu-West_arab_2019_09,GM-M_Lower-Fuladu-West_arab_2019_Q3
2,VBS47726-6366STDY9854335,C0587,Kevin Opondo,"Gambia, The",Bansang,2019,9,13.434,-14.655,F,...,Janjanbureh,GM-M,Upper Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_09,GM-M_arab_2019_Q3,GM-M_Upper-Fuladu-West_arab_2019,GM-M_Upper-Fuladu-West_arab_2019_09,GM-M_Upper-Fuladu-West_arab_2019_Q3
3,VBS47729-6366STDY9854338,C2710,Kevin Opondo,"Gambia, The",Boiram,2019,10,13.503,-14.926,F,...,Janjanbureh,GM-M,Lower Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_10,GM-M_arab_2019_Q4,GM-M_Lower-Fuladu-West_arab_2019,GM-M_Lower-Fuladu-West_arab_2019_10,GM-M_Lower-Fuladu-West_arab_2019_Q4
4,VBS47731-6366STDY9854340,C2524,Kevin Opondo,"Gambia, The",Bansang,2019,9,13.434,-14.655,F,...,Janjanbureh,GM-M,Upper Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_09,GM-M_arab_2019_Q3,GM-M_Upper-Fuladu-West_arab_2019,GM-M_Upper-Fuladu-West_arab_2019_09,GM-M_Upper-Fuladu-West_arab_2019_Q3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309,VBS48167-6366STDY9854768,W1491,Kevin Opondo,"Gambia, The",Essau,2019,10,13.481,-16.515,F,...,Kerewan,GM-N,Lower Niumi,arabiensis,GM-N_arab_2019,GM-N_arab_2019_10,GM-N_arab_2019_Q4,GM-N_Lower-Niumi_arab_2019,GM-N_Lower-Niumi_arab_2019_10,GM-N_Lower-Niumi_arab_2019_Q4
310,VBS48171-6366STDY9854772,W2321,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.290,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
311,VBS48173-6366STDY9854774,W0382,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3
312,VBS48174-6366STDY9854775,W1168,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3
313,VBS48175-6366STDY9854776,W1807,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.290,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3

### **COE locus CNV HMM -- Supplementary Figure S8**

In [ ]:
coe_region = "2L:37,233,000-37,330,000"
coe_region_extended = "2L:37,217,000-37,335,000"

In [ ]:
ag3.plot_cnv_hmm_heatmap(
    region=coe_region_extended,
    sample_query=gambia_sample_query,
    row_height=3
)

GridPlot(id='p1968', ...)

### **COE locus CNV HMM / Random sample / Selected cohorts-- Supplementary Figure S9**

In [ ]:
# sample with Dup14 only
df_samples_gambia.query("sample_id == 'VBS48045-6366STDY9854645'")

,sample_id,partner_sample_id,contributor,country,location,year,month,latitude,longitude,sex_call,...,admin1_name,admin1_iso,admin2_name,taxon,cohort_admin1_year,cohort_admin1_month,cohort_admin1_quarter,cohort_admin2_year,cohort_admin2_month,cohort_admin2_quarter
227,VBS48045-6366STDY9854645,C3531,Kevin Opondo,"Gambia, The",Saruja,2019,11,13.551,-14.913,F,...,Janjanbureh,GM-M,Lower Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_11,GM-M_arab_2019_Q4,GM-M_Lower-Fuladu-West_arab_2019,GM-M_Lower-Fuladu-West_arab_2019_11,GM-M_Lower-Fuladu-West_arab_2019_Q4

In [ ]:
ag3.plot_cnv_hmm_coverage(sample='VBS48045-6366STDY9854645', sample_set='1272-VO-GM-OPONDO-VMF00160', region=coe_region_extended)

GridPlot(id='p1244', ...)

In [ ]:
hmm = ag3.cnv_hmm(region="2L", sample_sets="1272-VO-GM-OPONDO-VMF00160").set_index(samples="sample_id")
hmm

<xarray.Dataset> Size: 244MB
Dimensions:                   (variants: 164548, samples: 164)
Coordinates:
  * samples                   (samples) object 1kB 'VBS47724-6366STDY9854333'...
    variant_position          (variants) int32 658kB dask.array<chunksize=(65536,), meta=np.ndarray>
    variant_end               (variants) int32 658kB dask.array<chunksize=(65536,), meta=np.ndarray>
    variant_contig            (variants) uint8 165kB dask.array<chunksize=(164548,), meta=np.ndarray>
Dimensions without coordinates: variants
Data variables:
    call_CN                   (variants, samples) int8 27MB dask.array<chunksize=(65536, 63), meta=np.ndarray>
    call_RawCov               (variants, samples) int32 108MB dask.array<chunksize=(65536, 63), meta=np.ndarray>
    call_NormCov              (variants, samples) float32 108MB dask.array<chunksize=(65536, 63), meta=np.ndarray>
    sample_coverage_variance  (samples) float32 656B dask.array<chunksize=(164,), meta=np.ndarray>
    sample_is_high_variance   (samples) bool 164B dask.array<chunksize=(164,), meta=np.ndarray>
Attributes:
    contigs:  ('2R', '2L', '3R', '3L', 'X')

In [ ]:
# samples from Jeshwang

df_jw = df_samples_gambia.query("sample_set == '1272-VO-GM-OPONDO-VMF00160' and taxon == 'arabiensis' and admin2_name == 'Jeshwang'")
df_jw

,sample_id,partner_sample_id,contributor,country,location,year,month,latitude,longitude,sex_call,...,admin1_name,admin1_iso,admin2_name,taxon,cohort_admin1_year,cohort_admin1_month,cohort_admin1_quarter,cohort_admin2_year,cohort_admin2_month,cohort_admin2_quarter
89,VBS47876-6366STDY9854479,W2544,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3
91,VBS47879-6366STDY9854481,W0672,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3
92,VBS47880-6366STDY9854482,W2502,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3
93,VBS47881-6366STDY9854483,W1953,Kevin Opondo,"Gambia, The",Ebotown,2019,9,13.438,-16.674,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3
94,VBS47882-6366STDY9854484,W0593,Kevin Opondo,"Gambia, The",Ebotown,2019,9,13.438,-16.674,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,VBS48147-6366STDY9854749,W2195,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3
300,VBS48149-6366STDY9854751,W2835,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3
305,VBS48158-6366STDY9854760,W0659,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3
311,VBS48173-6366STDY9854774,W0382,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3
312,VBS48174-6366STDY9854775,W1168,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3

In [ ]:
sample_names_jw = ['VBS47876-6366STDY9854479', 'VBS47881-6366STDY9854483', 'VBS48147-6366STDY9854749', 'VBS48158-6366STDY9854760', 'VBS48174-6366STDY9854775']

In [ ]:
for s in sample_names_jw:
    ag3.plot_cnv_hmm_coverage(s, sample_set='1272-VO-GM-OPONDO-VMF00160', region=coe_region_extended)

In [ ]:
# samples from Kombo central
df_kc = df_samples_gambia.query("sample_set == '1272-VO-GM-OPONDO-VMF00160' and taxon == 'arabiensis' and admin2_name == 'Kombo Central'")
df_kc

,sample_id,partner_sample_id,contributor,country,location,year,month,latitude,longitude,sex_call,...,admin1_name,admin1_iso,admin2_name,taxon,cohort_admin1_year,cohort_admin1_month,cohort_admin1_quarter,cohort_admin2_year,cohort_admin2_month,cohort_admin2_quarter
90,VBS47878-6366STDY9854480,W2335,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
95,VBS47884-6366STDY9854485,W2439,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
100,VBS47890-6366STDY9854490,W1817,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
109,VBS47901-6366STDY9854499,W1821,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
112,VBS47904-6366STDY9854502,W2355,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
114,VBS47906-6366STDY9854504,W1692,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
118,VBS47910-6366STDY9854508,W2430,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
122,VBS47914-6366STDY9854512,W2145,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
129,VBS47921-6366STDY9854521,W1723,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
130,VBS47922-6366STDY9854522,W2347,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
137,VBS47930-6366STDY9854529,W1739,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
146,VBS47939-6366STDY9854538,W0714,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
155,VBS47948-6366STDY9854547,W2653,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
156,VBS47949-6366STDY9854548,W1023,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
162,VBS47955-6366STDY9854554,W0715,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
178,VBS47972-6366STDY9854570,W1711,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
181,VBS47975-6366STDY9854573,W1024,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
185,VBS47980-6366STDY9854578,W2657,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
188,VBS47983-6366STDY9854581,W2337,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
189,VBS47984-6366STDY9854582,W1439,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
190,VBS47985-6366STDY9854583,W2351,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
193,VBS47988-6366STDY9854586,W2328,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
195,VBS47990-6366STDY9854588,W1824,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
302,VBS48154-6366STDY9854756,W1051,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
303,VBS48155-6366STDY9854757,W1735,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
306,VBS48162-6366STDY9854764,W2596,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
310,VBS48171-6366STDY9854772,W2321,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
313,VBS48175-6366STDY9854776,W1807,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.29,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3

In [ ]:
sample_names_kc = ['VBS47878-6366STDY9854480', 'VBS47906-6366STDY9854504', 'VBS47975-6366STDY9854573', 'VBS48154-6366STDY9854756', 'VBS48175-6366STDY9854776']

In [ ]:
for s in sample_names_kc:
    ag3.plot_cnv_hmm_coverage(s, sample_set='1272-VO-GM-OPONDO-VMF00160', region=coe_region_extended)

In [ ]:
# samples from Basse
df_bs = df_samples_gambia.query("sample_set == '1272-VO-GM-OPONDO-VMF00160' and taxon == 'arabiensis' and admin2_name == 'Basse'")
df_bs

,sample_id,partner_sample_id,contributor,country,location,year,month,latitude,longitude,sex_call,...,admin1_name,admin1_iso,admin2_name,taxon,cohort_admin1_year,cohort_admin1_month,cohort_admin1_quarter,cohort_admin2_year,cohort_admin2_month,cohort_admin2_quarter
41,VBS47793-6366STDY9854400,E0120,Kevin Opondo,"Gambia, The",Kaba Kamma,2019,9,13.305,-14.207,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
43,VBS47796-6366STDY9854403,E3092,Kevin Opondo,"Gambia, The",Santo Su,2019,9,13.307,-14.220,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
51,VBS47814-6366STDY9854418,E2642,Kevin Opondo,"Gambia, The",Santo Su,2019,9,13.307,-14.220,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
58,VBS47826-6366STDY9854432,E0858,Kevin Opondo,"Gambia, The",Sabi,2019,9,13.237,-14.196,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
61,VBS47829-6366STDY9854435,E0094,Kevin Opondo,"Gambia, The",Kaba Kamma,2019,9,13.305,-14.207,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
68,VBS47840-6366STDY9854445,E2474,Kevin Opondo,"Gambia, The",Sabi,2019,9,13.237,-14.196,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
70,VBS47842-6366STDY9854447,E0804,Kevin Opondo,"Gambia, The",Sabi,2019,9,13.237,-14.196,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
71,VBS47844-6366STDY9854449,E0084,Kevin Opondo,"Gambia, The",Kaba Kamma,2019,9,13.305,-14.207,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
73,VBS47846-6366STDY9854451,E0775,Kevin Opondo,"Gambia, The",Sabi,2019,9,13.237,-14.196,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
78,VBS47852-6366STDY9854457,E2591,Kevin Opondo,"Gambia, The",Santo Su,2019,9,13.307,-14.220,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
86,VBS47870-6366STDY9854473,E2330,Kevin Opondo,"Gambia, The",Sabi,2019,9,13.237,-14.196,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
87,VBS47871-6366STDY9854474,E2592,Kevin Opondo,"Gambia, The",Santo Su,2019,9,13.307,-14.220,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
88,VBS47872-6366STDY9854475,E2594,Kevin Opondo,"Gambia, The",Santo Su,2019,9,13.307,-14.220,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
235,VBS48056-6366STDY9854656,E3076,Kevin Opondo,"Gambia, The",Santo Su,2019,9,13.307,-14.220,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
236,VBS48057-6366STDY9854657,E4468,Kevin Opondo,"Gambia, The",Sabi,2019,9,13.237,-14.196,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
238,VBS48059-6366STDY9854659,E3132,Kevin Opondo,"Gambia, The",Santo Su,2019,9,13.307,-14.220,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
241,VBS48063-6366STDY9854663,E4435,Kevin Opondo,"Gambia, The",Sabi,2019,9,13.237,-14.196,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
242,VBS48064-6366STDY9854664,E4257,Kevin Opondo,"Gambia, The",Sabi,2019,9,13.237,-14.196,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
243,VBS48065-6366STDY9854665,E0851,Kevin Opondo,"Gambia, The",Sabi,2019,9,13.237,-14.196,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
245,VBS48067-6366STDY9854667,E2236,Kevin Opondo,"Gambia, The",Sabi,2019,9,13.237,-14.196,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
247,VBS48071-6366STDY9854671,E0838,Kevin Opondo,"Gambia, The",Sabi,2019,9,13.237,-14.196,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
253,VBS48077-6366STDY9854677,E3039,Kevin Opondo,"Gambia, The",Santo Su,2019,9,13.307,-14.220,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
255,VBS48079-6366STDY9854679,E2285,Kevin Opondo,"Gambia, The",Sabi,2019,9,13.237,-14.196,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
267,VBS48099-6366STDY9854699,E3078,Kevin Opondo,"Gambia, The",Santo Su,2019,9,13.307,-14.220,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
268,VBS48100-6366STDY9854700,E0227,Kevin Opondo,"Gambia, The",Santo Su,2019,9,13.307,-14.220,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
278,VBS48117-6366STDY9854719,E2292,Kevin Opondo,"Gambia, The",Sabi,2019,9,13.237,-14.196,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
281,VBS48120-6366STDY9854722,E4351,Kevin Opondo,"Gambia, The",Sabi,2019,9,13.237,-14.196,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3
284,VBS48126-6366STDY9854728,E0962,Kevin Opondo,"Gambia, The",Sabi,2019,9,13.237,-14.196,F,...,Basse,GM-U,Basse,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Basse_arab_2019,GM-U_Basse_arab_2019_09,GM-U_Basse_arab_2019_Q3

In [ ]:
sample_names_bs = ['VBS47793-6366STDY9854400', 'VBS47840-6366STDY9854445', 'VBS47852-6366STDY9854457', 'VBS48063-6366STDY9854663', 'VBS48100-6366STDY9854700']

In [ ]:
for s in sample_names_bs:
    ag3.plot_cnv_hmm_coverage(s, sample_set='1272-VO-GM-OPONDO-VMF00160', region=coe_region_extended)

In [ ]:
# samples from Jimara
df_ji = df_samples_gambia.query("sample_set == '1272-VO-GM-OPONDO-VMF00160' and taxon == 'arabiensis' and admin2_name == 'Jimara'")
df_ji

,sample_id,partner_sample_id,contributor,country,location,year,month,latitude,longitude,sex_call,...,admin1_name,admin1_iso,admin2_name,taxon,cohort_admin1_year,cohort_admin1_month,cohort_admin1_quarter,cohort_admin2_year,cohort_admin2_month,cohort_admin2_quarter
39,VBS47790-6366STDY9854397,E2391,Kevin Opondo,"Gambia, The",Gambisara,2019,9,13.236,-14.310,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
40,VBS47792-6366STDY9854399,E1699,Kevin Opondo,"Gambia, The",Damba kunda Kuta,2019,10,13.260,-14.268,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_10,GM-U_arab_2019_Q4,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_10,GM-U_Jimara_arab_2019_Q4
42,VBS47794-6366STDY9854401,E0239,Kevin Opondo,"Gambia, The",Sotuma sere,2019,9,13.294,-14.320,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
46,VBS47806-6366STDY9854410,E2894,Kevin Opondo,"Gambia, The",Gambisara,2019,9,13.236,-14.310,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
47,VBS47807-6366STDY9854411,E0277,Kevin Opondo,"Gambia, The",Sotuma sere,2019,9,13.294,-14.320,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
49,VBS47809-6366STDY9854413,E1220,Kevin Opondo,"Gambia, The",Kossemar,2019,9,13.331,-14.376,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
50,VBS47810-6366STDY9854414,E0463,Kevin Opondo,"Gambia, The",Damba kunda Kuta,2019,10,13.260,-14.268,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_10,GM-U_arab_2019_Q4,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_10,GM-U_Jimara_arab_2019_Q4
52,VBS47817-6366STDY9854421,E3984,Kevin Opondo,"Gambia, The",Gambisara,2019,9,13.236,-14.310,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
55,VBS47823-6366STDY9854429,E0241,Kevin Opondo,"Gambia, The",Sotuma sere,2019,9,13.294,-14.320,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
56,VBS47824-6366STDY9854430,E1001,Kevin Opondo,"Gambia, The",Kossemar,2019,9,13.331,-14.376,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
57,VBS47825-6366STDY9854431,E0262,Kevin Opondo,"Gambia, The",Sotuma sere,2019,9,13.294,-14.320,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
59,VBS47827-6366STDY9854433,E4097,Kevin Opondo,"Gambia, The",Gambisara,2019,9,13.236,-14.310,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
60,VBS47828-6366STDY9854434,E0498,Kevin Opondo,"Gambia, The",Damba kunda Kuta,2019,10,13.260,-14.268,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_10,GM-U_arab_2019_Q4,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_10,GM-U_Jimara_arab_2019_Q4
62,VBS47830-6366STDY9854436,E2892,Kevin Opondo,"Gambia, The",Gambisara,2019,9,13.236,-14.310,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
63,VBS47831-6366STDY9854437,E0459,Kevin Opondo,"Gambia, The",Damba kunda Kuta,2019,10,13.260,-14.268,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_10,GM-U_arab_2019_Q4,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_10,GM-U_Jimara_arab_2019_Q4
74,VBS47847-6366STDY9854452,E1011,Kevin Opondo,"Gambia, The",Kossemar,2019,9,13.331,-14.376,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
77,VBS47851-6366STDY9854456,E1003,Kevin Opondo,"Gambia, The",Kossemar,2019,9,13.331,-14.376,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
80,VBS47856-6366STDY9854460,E1274,Kevin Opondo,"Gambia, The",Kossemar,2019,9,13.331,-14.376,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
81,VBS47857-6366STDY9854461,E0281,Kevin Opondo,"Gambia, The",Sotuma sere,2019,9,13.294,-14.320,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
84,VBS47863-6366STDY9854466,E4099,Kevin Opondo,"Gambia, The",Gambisara,2019,9,13.236,-14.310,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
239,VBS48061-6366STDY9854661,E0542,Kevin Opondo,"Gambia, The",Damba kunda Kuta,2019,10,13.260,-14.268,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_10,GM-U_arab_2019_Q4,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_10,GM-U_Jimara_arab_2019_Q4
251,VBS48075-6366STDY9854675,E0335,Kevin Opondo,"Gambia, The",Gambisara,2019,9,13.236,-14.310,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
252,VBS48076-6366STDY9854676,E1969,Kevin Opondo,"Gambia, The",Kossemar,2019,9,13.331,-14.376,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
258,VBS48085-6366STDY9854685,E1908,Kevin Opondo,"Gambia, The",Kossemar,2019,9,13.331,-14.376,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
259,VBS48086-6366STDY9854686,E4087,Kevin Opondo,"Gambia, The",Gambisara,2019,9,13.236,-14.310,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
262,VBS48089-6366STDY9854689,E2414,Kevin Opondo,"Gambia, The",Gambisara,2019,9,13.236,-14.310,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
265,VBS48097-6366STDY9854697,E1248,Kevin Opondo,"Gambia, The",Kossemar,2019,9,13.331,-14.376,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
271,VBS48103-6366STDY9854703,E4078,Kevin Opondo,"Gambia, The",Gambisara,2019,9,13.236,-14.310,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
272,VBS48104-6366STDY9854704,E3975,Kevin Opondo,"Gambia, The",Gambisara,2019,9,13.236,-14.310,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
273,VBS48105-6366STDY9854705,E0333,Kevin Opondo,"Gambia, The",Gambisara,2019,9,13.236,-14.310,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
274,VBS48106-6366STDY9854706,E4046,Kevin Opondo,"Gambia, The",Gambisara,2019,9,13.236,-14.310,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
276,VBS48114-6366STDY9854716,E1602,Kevin Opondo,"Gambia, The",Damba kunda Kuta,2019,10,13.260,-14.268,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_10,GM-U_arab_2019_Q4,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_10,GM-U_Jimara_arab_2019_Q4
280,VBS48119-6366STDY9854721,E1062,Kevin Opondo,"Gambia, The",Kossemar,2019,9,13.331,-14.376,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
285,VBS48127-6366STDY9854729,E2001,Kevin Opondo,"Gambia, The",Kossemar,2019,9,13.331,-14.376,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
286,VBS48128-6366STDY9854730,E3957,Kevin Opondo,"Gambia, The",Gambisara,2019,9,13.236,-14.310,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
290,VBS48133-6366STDY9854735,E3528,Kevin Opondo,"Gambia, The",Gambisara,2019,9,13.236,-14.310,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3
292,VBS48135-6366STDY9854737,E1949,Kevin Opondo,"Gambia, The",Kossemar,2019,9,13.331,-14.376,F,...,Basse,GM-U,Jimara,arabiensis,GM-U_arab_2019,GM-U_arab_2019_09,GM-U_arab_2019_Q3,GM-U_Jimara_arab_2019,GM-U_Jimara_arab_2019_09,GM-U_Jimara_arab_2019_Q3

In [ ]:
sample_names_ji = ['VBS47790-6366STDY9854397', 'VBS47807-6366STDY9854411', 'VBS48061-6366STDY9854661', 'VBS48114-6366STDY9854716', 'VBS48135-6366STDY9854737']

In [ ]:
for s in sample_names_ji:
    ag3.plot_cnv_hmm_coverage(s, sample_set='1272-VO-GM-OPONDO-VMF00160', region=coe_region_extended)