# **Genomic analysis of _Anopheles arabiensis_ in The Gambia**

### **Figure 1a. Population Sampling**

- In this section, we cover population sampling of _Anopheles arabiensis_ collected in the The Gambia.
- We summarise the information on the available samples in terms of numbers of samples available from different locations and collection years.
- The distribution of samples is represented in maps and graphs.

In [1]:
!pip install -q malariagen_data

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 34.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.1/216.1 kB 16.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.7/71.7 kB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 106.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 106.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 775.9/775.9 kB 42.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 112.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.8/25.8 MB 80.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 108.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.3/211.3 kB 17.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 88.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 88.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 52.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.3/87.3 kB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.0/228.0 kB 16.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.3/14.3 MB 104.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 68.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 kB 6.4 MB/s eta 0:00:00
  Building wheel for dash-cytoscape (setup.py) ... done
  Building wheel for asciitree (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
panel 1.8.4 requires bokeh<3.9.0,>=3.7.0, but you have bokeh 3.6.3 which is incompatible.

In [35]:
# Import libraries
import os
import re
import plotly.express as px
import pandas as pd
import ipyleaflet
from ipyleaflet import basemaps, Map, CircleMarker, LayersControl, basemaps, basemap_to_tiles, LegendControl, Marker, DivIcon
from ipywidgets import HTML

In [3]:
import malariagen_data

In [4]:
ag3=malariagen_data.Ag3()
ag3

<MalariaGEN Ag3 API client>
Storage URL                           : gs://vo_agam_release_master_us_central1/
Data releases available               : 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12, 3.13, 3.14
Results cache                         : None
Cohorts analysis                      : 20250815
AIM analysis                          : 20220528
Site filters analysis                 : dt_20200416
Software version                      : malariagen_data 15.5.0
Client location                       : District of Columbia, United States (Google Cloud us-other)
Data filtered to unrestricted use only: False
Data filtered to surveillance use only: False
Relevant data releases                : 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12, 3.13, 3.14
---
Please note that data are subject to terms of use,
for more information see https://www.malariagen.net/data
or contact support@malariagen.net. For API documentation see
https://malariagen.github.io/malariagen-data-python/v15.5.0/Ag3.html

In [8]:
gambia_sample_query = "country == 'Gambia, The' and sample_set == '1272-VO-GM-OPONDO-VMF00160'"

In [9]:
# access metadata
df_samples_gambia = ag3.sample_metadata(sample_query=gambia_sample_query)
df_samples_gambia

,sample_id,partner_sample_id,contributor,country,location,year,month,latitude,longitude,sex_call,...,admin1_name,admin1_iso,admin2_name,taxon,cohort_admin1_year,cohort_admin1_month,cohort_admin1_quarter,cohort_admin2_year,cohort_admin2_month,cohort_admin2_quarter
0,VBS47721-6366STDY9854330,C1161,Kevin Opondo,"Gambia, The",Jareng,2019,9,13.620,-15.190,F,...,Janjanbureh,GM-M,Niamina East,coluzzii,GM-M_colu_2019,GM-M_colu_2019_09,GM-M_colu_2019_Q3,GM-M_Niamina-East_colu_2019,GM-M_Niamina-East_colu_2019_09,GM-M_Niamina-East_colu_2019_Q3
1,VBS47723-6366STDY9854332,C0454,Kevin Opondo,"Gambia, The",Dongoroba,2019,9,13.380,-15.294,F,...,Mansakonko,GM-L,Jarra East,arabiensis,GM-L_arab_2019,GM-L_arab_2019_09,GM-L_arab_2019_Q3,GM-L_Jarra-East_arab_2019,GM-L_Jarra-East_arab_2019_09,GM-L_Jarra-East_arab_2019_Q3
2,VBS47724-6366STDY9854333,C2526,Kevin Opondo,"Gambia, The",Bansang,2019,9,13.434,-14.655,F,...,Janjanbureh,GM-M,Upper Fuladu West,unassigned,NaN,NaN,NaN,NaN,NaN,NaN
3,VBS47725-6366STDY9854334,C2409,Kevin Opondo,"Gambia, The",Kerewan,2019,9,13.515,-14.896,F,...,Janjanbureh,GM-M,Lower Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_09,GM-M_arab_2019_Q3,GM-M_Lower-Fuladu-West_arab_2019,GM-M_Lower-Fuladu-West_arab_2019_09,GM-M_Lower-Fuladu-West_arab_2019_Q3
4,VBS47726-6366STDY9854335,C0587,Kevin Opondo,"Gambia, The",Bansang,2019,9,13.434,-14.655,F,...,Janjanbureh,GM-M,Upper Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_09,GM-M_arab_2019_Q3,GM-M_Upper-Fuladu-West_arab_2019,GM-M_Upper-Fuladu-West_arab_2019_09,GM-M_Upper-Fuladu-West_arab_2019_Q3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377,VBS48172-6366STDY9854773,W2393,Kevin Opondo,"Gambia, The",Bullock,2019,9,13.181,-16.414,F,...,Brikama,GM-W,Foni Brefet,bissau,GM-W_biss_2019,GM-W_biss_2019_09,GM-W_biss_2019_Q3,GM-W_Foni-Brefet_biss_2019,GM-W_Foni-Brefet_biss_2019_09,GM-W_Foni-Brefet_biss_2019_Q3
378,VBS48173-6366STDY9854774,W0382,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3
379,VBS48174-6366STDY9854775,W1168,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3
380,VBS48175-6366STDY9854776,W1807,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.290,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
381,VBS48181-6366STDY9854780,C1106,Kevin Opondo,"Gambia, The",Kuntaur,2019,9,13.668,-14.889,F,...,Kuntaur,GM-M,Niani,coluzzii,GM-M_colu_2019,GM-M_colu_2019_09,GM-M_colu_2019_Q3,GM-M_Niani_colu_2019,GM-M_Niani_colu_2019_09,GM-M_Niani_colu_2019_Q3

In [5]:
ag3.sample_metadata(sample_query="country == 'Gambia, The' and taxon == 'arabiensis'").groupby("cohort_admin2_year").size()

cohort_admin2_year
GM-L_Jarra-East_arab_2001             1
GM-L_Jarra-East_arab_2019             6
GM-L_Jarra-West_arab_2005             2
GM-L_Kiang-West_arab_2005            42
GM-M_Janjanbureh_arab_2021            2
GM-M_Lower-Fuladu-West_arab_2019     53
GM-M_Niamina-East_arab_2019          17
GM-M_Niamina-West_arab_2019           8
GM-M_Niani_arab_2019                243
GM-M_Nianija_arab_2014                1
GM-M_Nianija_arab_2019               27
GM-M_Sami_arab_2019                  90
GM-M_Upper-Fuladu-West_arab_2019     12
GM-N_Illiasa_arab_2019               20
GM-N_Illiasa_arab_2021                2
GM-N_Lower-Badibu_arab_2005           7
GM-N_Lower-Niumi_arab_2019           65
GM-U_Basse_arab_2019                 28
GM-U_Jimara_arab_2019               120
GM-U_Sandu_arab_2019                  8
GM-U_Tumana_arab_2019               340
GM-U_Wuli-East_arab_2019              1
GM-W_Bakau_arab_2019                  6
GM-W_Foni-Brefet_arab_2019            4
GM-W_Jeshwang_arab_2019              77
GM-W_Kombo-Central_arab_2019         28
GM-W_Kombo-Central_arab_2021          2
GM-W_Kombo-East_arab_2005            11
GM-W_Kombo-South_arab_2005            3
GM-W_Serrekunda-East_arab_2019        6
GM-W_Serrekunda-West_arab_2019        4
dtype: int64

In [12]:
# total number of mosquitoes collected by species level
df_gambia = ag3.count_samples(sample_query=gambia_sample_query)
df_gambia

taxon                                                      arabiensis  bissau  \
country     admin1_iso admin1_name admin2_name       year
Gambia, The GM-L       Mansakonko  Jarra East        2001           1       0
                                                     2019           6       0
            GM-M       Janjanbureh Lower Fuladu West 2019          51       0
                                   Niamina Dankunku  2019           0       1
                                   Niamina East      2019          10       0
                                   Niamina West      2019           8       0
                                   Upper Fuladu West 2019          12       0
                       Kuntaur     Niani             2019           4       0
            GM-N       Kerewan     Illiasa           2019           3       0
                                   Lower Niumi       2019          13       0
            GM-U       Basse       Basse             2019          28       0
                                   Jimara            2019          37       1
                                   Sandu             2019           8       0
                                   Tumana            2019          21       0
                                   Wuli East         2019           1       0
            GM-W       Brikama     Foni Brefet       2019           1       4
                                   Kombo Central     2019          28       0
                       Kanifing    Bakau             2019           6       0
                                   Jeshwang          2019          77       0

taxon                                                      coluzzii  gambiae  \
country     admin1_iso admin1_name admin2_name       year
Gambia, The GM-L       Mansakonko  Jarra East        2001         0        0
                                                     2019         3        0
            GM-M       Janjanbureh Lower Fuladu West 2019        12        1
                                   Niamina Dankunku  2019         0        0
                                   Niamina East      2019         6        0
                                   Niamina West      2019         1        2
                                   Upper Fuladu West 2019         4        0
                       Kuntaur     Niani             2019         4        0
            GM-N       Kerewan     Illiasa           2019         0        0
                                   Lower Niumi       2019         0        0
            GM-U       Basse       Basse             2019         3        4
                                   Jimara            2019         3       10
                                   Sandu             2019         1        2
                                   Tumana            2019         0        0
                                   Wuli East         2019         0        0
            GM-W       Brikama     Foni Brefet       2019         0        0
                                   Kombo Central     2019         0        0
                       Kanifing    Bakau             2019         0        0
                                   Jeshwang          2019         0        0

taxon                                                      unassigned
country     admin1_iso admin1_name admin2_name       year
Gambia, The GM-L       Mansakonko  Jarra East        2001           0
                                                     2019           0
            GM-M       Janjanbureh Lower Fuladu West 2019           0
                                   Niamina Dankunku  2019           0
                                   Niamina East      2019           1
                                   Niamina West      2019           0
                                   Upper Fuladu West 2019           1
                       Kuntaur     Niani             2019           0
            GM-N       Kerewan     Illiasa           2019           0
                                   Lower Niumi       2019           0
            GM-U       Basse       Basse             2019           1
                                   Jimara            2019           1
                                   Sandu             2019           0
                                   Tumana            2019           1
                                   Wuli East         2019           0
            GM-W       Brikama     Foni Brefet       2019           0
                                   Kombo Central     2019           0
                       Kanifing    Bakau             2019           0
                                   Jeshwang          2019           0

In [14]:
gambia_region_taxon = (
    df_samples_gambia
    .pivot_table(
        index="admin1_name",
        columns="taxon",
        values="sample_id",
        aggfunc="count",
        fill_value=0
    )
)
gambia_region_taxon

taxon        arabiensis  bissau  coluzzii  gambiae  unassigned
admin1_name
Basse                95       1         7       16           3
Brikama              29       4         0        0           0
Janjanbureh          81       1        23        3           2
Kanifing             83       0         0        0           0
Kerewan              16       0         0        0           0
Kuntaur               4       0         4        0           0
Mansakonko            7       0         3        0           0

In [16]:
admin1_fig = px.bar(gambia_region_taxon, height=600, width=800)
admin1_fig.update_layout(
    title="Total genomes sequenced",
    yaxis_title="Number of genomes",
    xaxis_title="Regions",
)
admin1_fig

In [17]:
gambia_location_taxon = (
    df_samples_gambia
    .pivot_table(
        index=["location", "latitude", "longitude"],
        columns=["taxon"],
        values="sample_id",
        aggfunc="count",
        fill_value=0,
    )
)

gambia_location_taxon

,,taxon,arabiensis,bissau,coluzzii,gambiae,unassigned
location,latitude,longitude,,,,,
Baja Kunda,13.470,-14.050,1,0,0,0,0
Bakau,13.476,-16.674,6,0,0,0,0
Bansang,13.434,-14.655,12,0,4,0,1
Boiram,13.503,-14.926,12,0,0,1,0
Brikama-A,13.290,-16.657,28,0,0,0,0
Bullock,13.181,-16.414,1,4,0,0,0
Damba kunda Kuta,13.260,-14.268,6,1,0,4,1
Dongoroba,13.380,-15.294,7,0,3,0,0
Ebotown,13.438,-16.674,19,0,0,0,0
Essau,13.481,-16.515,13,0,0,0,0
Farafenni,13.572,-15.599,3,0,0,0,0
Gambisara,13.236,-14.310,15,0,2,4,0
Jakhali,13.546,-14.972,6,0,5,0,0
Jareng,13.620,-15.190,5,0,6,0,1
Kaba Kamma,13.305,-14.207,3,0,3,0,0
Katamima,13.548,-15.291,0,0,0,1,0
Kerewan,13.515,-14.896,5,0,0,0,0
Kossemar,13.331,-14.376,11,0,1,2,0
Kumbija,13.606,-15.233,8,0,1,1,0
Kuntaur,13.668,-14.889,2,0,4,0,0
Medina,13.608,-15.281,0,1,0,0,0
Nyakoi Madina,13.308,-14.010,5,0,0,0,0
Nyanga Batang,13.785,-15.010,2,0,0,0,0
Sabi,13.237,-14.196,15,0,0,4,1
Sankulay kunda,13.514,-14.762,8,0,3,0,0
Santo Su,13.307,-14.220,10,0,0,0,0
Sapu,13.559,-14.945,7,0,4,0,0
Sare Alpha,13.359,-13.980,1,0,0,0,0
Sare Demba,13.433,-14.317,8,0,1,2,0
Sare Silli,13.619,-15.124,5,0,0,0,0
Saruja,13.551,-14.913,13,0,0,0,0
Sotuma sere,13.294,-14.320,5,0,0,0,0
Tallinding,13.437,-16.670,58,0,0,0,0
Tambansang,13.376,-14.157,7,0,0,0,1
Tuba Simoto,13.368,-13.988,8,0,0,0,0

In [23]:
# arabiensis

ag3.plot_samples_interactive_map(
    sample_query="taxon == 'arabiensis' and country == 'Gambia, The' and sample_set == '1272-VO-GM-OPONDO-VMF00160'",
    center=(13.5, -15),
    zoom=9,
    basemap=basemaps.OpenStreetMap.Mapnik,
    min_samples=2,
)

Map(center=[13.5, -15], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_…

Samples color mappings

In [24]:
# Define color mapping for each admin1 unit
color_mapping_admin1 = {
    'Basse':'teal',
    'Janjanbureh':'navy',
    'Kuntaur':'firebrick',
    'Mansakonko':'plum',
    'Kerewan':'olive',
    'Brikama':'deeppink',
    'Kanifing':'purple'
}

In [25]:
# Define color mapping for each admin2 unit
color_mapping_admin2 = {
    'Jarra East': '#8e8c84',
    'Lower Fuladu West': '#7f7f7f',
    'Upper Fuladu West': '#6b705c',
    'Niani': '#4a4e4d',
    'Niamina East': '#3b5c40',
    'Jimara': '#8e7d32',
    'Basse': '#a95b29',
    'Wuli East': '#b64d3b',
    'Tumana': '#8a4b39',
    'Niamina West': '#6f4e37',
    'Sandu': '#3e3a3a',
    'Jeshwang': '#a4c9e2',
    'Kombo Central': '#78aaff',
    'Lower Niumi': '#4d88ff',
    'Bakau': '#0077b6',
    'Illiasa': '#0096c7',
    'Foni Brefet': '#00b4d8'
}

In [30]:
# access metadata
gm_arab_sample_query = "country == 'Gambia, The' and sample_set == '1272-VO-GM-OPONDO-VMF00160' and taxon == 'arabiensis'"

In [31]:
# access metadata
met_gambia_arab = ag3.sample_metadata(sample_query=gm_arab_sample_query)
met_gambia_arab

,sample_id,partner_sample_id,contributor,country,location,year,month,latitude,longitude,sex_call,...,admin1_name,admin1_iso,admin2_name,taxon,cohort_admin1_year,cohort_admin1_month,cohort_admin1_quarter,cohort_admin2_year,cohort_admin2_month,cohort_admin2_quarter
0,VBS47723-6366STDY9854332,C0454,Kevin Opondo,"Gambia, The",Dongoroba,2019,9,13.380,-15.294,F,...,Mansakonko,GM-L,Jarra East,arabiensis,GM-L_arab_2019,GM-L_arab_2019_09,GM-L_arab_2019_Q3,GM-L_Jarra-East_arab_2019,GM-L_Jarra-East_arab_2019_09,GM-L_Jarra-East_arab_2019_Q3
1,VBS47725-6366STDY9854334,C2409,Kevin Opondo,"Gambia, The",Kerewan,2019,9,13.515,-14.896,F,...,Janjanbureh,GM-M,Lower Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_09,GM-M_arab_2019_Q3,GM-M_Lower-Fuladu-West_arab_2019,GM-M_Lower-Fuladu-West_arab_2019_09,GM-M_Lower-Fuladu-West_arab_2019_Q3
2,VBS47726-6366STDY9854335,C0587,Kevin Opondo,"Gambia, The",Bansang,2019,9,13.434,-14.655,F,...,Janjanbureh,GM-M,Upper Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_09,GM-M_arab_2019_Q3,GM-M_Upper-Fuladu-West_arab_2019,GM-M_Upper-Fuladu-West_arab_2019_09,GM-M_Upper-Fuladu-West_arab_2019_Q3
3,VBS47729-6366STDY9854338,C2710,Kevin Opondo,"Gambia, The",Boiram,2019,10,13.503,-14.926,F,...,Janjanbureh,GM-M,Lower Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_10,GM-M_arab_2019_Q4,GM-M_Lower-Fuladu-West_arab_2019,GM-M_Lower-Fuladu-West_arab_2019_10,GM-M_Lower-Fuladu-West_arab_2019_Q4
4,VBS47731-6366STDY9854340,C2524,Kevin Opondo,"Gambia, The",Bansang,2019,9,13.434,-14.655,F,...,Janjanbureh,GM-M,Upper Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_09,GM-M_arab_2019_Q3,GM-M_Upper-Fuladu-West_arab_2019,GM-M_Upper-Fuladu-West_arab_2019_09,GM-M_Upper-Fuladu-West_arab_2019_Q3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,VBS48167-6366STDY9854768,W1491,Kevin Opondo,"Gambia, The",Essau,2019,10,13.481,-16.515,F,...,Kerewan,GM-N,Lower Niumi,arabiensis,GM-N_arab_2019,GM-N_arab_2019_10,GM-N_arab_2019_Q4,GM-N_Lower-Niumi_arab_2019,GM-N_Lower-Niumi_arab_2019_10,GM-N_Lower-Niumi_arab_2019_Q4
311,VBS48171-6366STDY9854772,W2321,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.290,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
312,VBS48173-6366STDY9854774,W0382,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3
313,VBS48174-6366STDY9854775,W1168,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3
314,VBS48175-6366STDY9854776,W1807,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.290,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3

In [32]:
# Apply color mapping to the metadata
met_gambia_arab['color1'] = met_gambia_arab['admin1_name'].map(color_mapping_admin1)

In [33]:
# Apply color mapping to the metadata
met_gambia_arab['color2'] = met_gambia_arab['admin2_name'].map(color_mapping_admin2)

In [34]:
met_gambia_arab

,sample_id,partner_sample_id,contributor,country,location,year,month,latitude,longitude,sex_call,...,admin2_name,taxon,cohort_admin1_year,cohort_admin1_month,cohort_admin1_quarter,cohort_admin2_year,cohort_admin2_month,cohort_admin2_quarter,color1,color2
0,VBS47723-6366STDY9854332,C0454,Kevin Opondo,"Gambia, The",Dongoroba,2019,9,13.380,-15.294,F,...,Jarra East,arabiensis,GM-L_arab_2019,GM-L_arab_2019_09,GM-L_arab_2019_Q3,GM-L_Jarra-East_arab_2019,GM-L_Jarra-East_arab_2019_09,GM-L_Jarra-East_arab_2019_Q3,plum,#8e8c84
1,VBS47725-6366STDY9854334,C2409,Kevin Opondo,"Gambia, The",Kerewan,2019,9,13.515,-14.896,F,...,Lower Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_09,GM-M_arab_2019_Q3,GM-M_Lower-Fuladu-West_arab_2019,GM-M_Lower-Fuladu-West_arab_2019_09,GM-M_Lower-Fuladu-West_arab_2019_Q3,navy,#7f7f7f
2,VBS47726-6366STDY9854335,C0587,Kevin Opondo,"Gambia, The",Bansang,2019,9,13.434,-14.655,F,...,Upper Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_09,GM-M_arab_2019_Q3,GM-M_Upper-Fuladu-West_arab_2019,GM-M_Upper-Fuladu-West_arab_2019_09,GM-M_Upper-Fuladu-West_arab_2019_Q3,navy,#6b705c
3,VBS47729-6366STDY9854338,C2710,Kevin Opondo,"Gambia, The",Boiram,2019,10,13.503,-14.926,F,...,Lower Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_10,GM-M_arab_2019_Q4,GM-M_Lower-Fuladu-West_arab_2019,GM-M_Lower-Fuladu-West_arab_2019_10,GM-M_Lower-Fuladu-West_arab_2019_Q4,navy,#7f7f7f
4,VBS47731-6366STDY9854340,C2524,Kevin Opondo,"Gambia, The",Bansang,2019,9,13.434,-14.655,F,...,Upper Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_09,GM-M_arab_2019_Q3,GM-M_Upper-Fuladu-West_arab_2019,GM-M_Upper-Fuladu-West_arab_2019_09,GM-M_Upper-Fuladu-West_arab_2019_Q3,navy,#6b705c
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,VBS48167-6366STDY9854768,W1491,Kevin Opondo,"Gambia, The",Essau,2019,10,13.481,-16.515,F,...,Lower Niumi,arabiensis,GM-N_arab_2019,GM-N_arab_2019_10,GM-N_arab_2019_Q4,GM-N_Lower-Niumi_arab_2019,GM-N_Lower-Niumi_arab_2019_10,GM-N_Lower-Niumi_arab_2019_Q4,olive,#4d88ff
311,VBS48171-6366STDY9854772,W2321,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.290,-16.657,F,...,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3,deeppink,#78aaff
312,VBS48173-6366STDY9854774,W0382,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3,purple,#a4c9e2
313,VBS48174-6366STDY9854775,W1168,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3,purple,#a4c9e2
314,VBS48175-6366STDY9854776,W1807,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.290,-16.657,F,...,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3,deeppink,#78aaff

In [36]:

# Create base map centered on The Gambia
streetmap = basemap_to_tiles(basemaps.OpenStreetMap)
m = Map(center=(13.4432, -15.3101), zoom=8)
m.add_layer(streetmap)

# Add translucent text labels
admin2_centroids = met_gambia_arab.groupby('admin2_name')[['latitude', 'longitude']].mean().reset_index()

# Define offsets for text box placement
lat_offset = 0.03   # positive = north, negative = south
lon_offset = 0.03  # positive = east, negative = west


for _, row in admin2_centroids.iterrows():
    color = color_mapping_admin2.get(row['admin2_name'], 'gray')

    label_html = f"""
    <div style="
        background: rgba(255, 255, 255, 0.5);
        border: 1.5px solid rgba(0, 0, 0, 0.4);
        border-radius: 15px;
        padding: 8px 12px;
        font-size: 12px;
        font-weight: bold;
        color: {color};
        text-align: center;
        white-space: nowrap;
        box-shadow: 0 0 8px rgba(0,0,0,0.25);
        #backdrop-filter: blur(2px);
        line-height: 1.3;
        width: max-content;
        pointer-events: none;
    ">
        {row['admin2_name']}
    </div>
    """

    # Shift label slightly south (below point) to reduce overlap
    label_marker = Marker(
        location=(row['latitude'] + lat_offset, row['longitude'] - lon_offset),
        icon=DivIcon(html=label_html, icon_size=(0, 0))
    )
    m.add_layer(label_marker)

# Add circle markers (on top of labels)
for _, row in met_gambia_arab.iterrows():
    color = color_mapping_admin2.get(row['admin2_name'], 'gray')

    marker = CircleMarker(
        location=(row['latitude'], row['longitude']),
        radius=5,
        color=color,
        fill_color=color,
        fill_opacity=1.5,
        weight=2
    )

    popup_html = HTML(f"""
        <b>Sample ID:</b> {row['sample_id']}<br>
        <b>Admin1 Name:</b> {row['admin1_name']}<br>
        <b>Admin2 Name:</b> {row['admin2_name']}<br>
        <b>Year:</b> {row['year']}<br>
        <b>Taxon:</b> {row['taxon']}
    """)
    marker.popup = popup_html
    m.add_layer(marker)

# Add legend and layer controls
#m.add_control(LayersControl(position='topright'))
#legend_items = {name: color for name, color in color_mapping_admin2.items()}
#legend = LegendControl(legend_items, name="Administrative Districts", position="bottomright")
#m.add_control(legend)

# Display map
m

Map(center=[13.4432, -15.3101], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'z…